set ("${PROJECT}_VERSION_MAJ" 1)
set ("${PROJECT}_VERSION_MIN" 1)
set ("${PROJECT}_VERSION_A" 1)
set ("${PROJECT}_VERSION_B" 1)
set ("${PROJECT}_VERSION" ${${PROJECT}_VERSION_MAJ}.${${PROJECT}_VERSION_MIN}.${${PROJECT}_VERSION_A}.${${PROJECT}_VERSION_B})

message(STATUS "Version: ${${PROJECT}_VERSION}")